# Generated by Django 5.0.14 on 2025-11-11 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(help_text='URL of the page visited', max_length=500)),
                ('visitor_ip', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500)),
                ('session_id', models.CharField(blank=True, help_text='Session ID for tracking unique visitors', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_p_timesta_b589d5_idx'), models.Index(fields=['page_url'], name='analytics_p_page_ur_ae0ca5_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('session_id', models.CharField(blank=True, help_text='Session ID for tracking unique visitors', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car View',
                'verbose_name_plural': 'Car Views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['car', '-timestamp'], name='analytics_c_car_id_d701fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=200)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Customer phone number', max_length=20)),
                ('message', models.TextField(help_text='Customer message/inquiry')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When was this inquiry resolved?', null=True)),
                ('car', models.ForeignKey(blank=True, help_text='Car this inquiry is about (optional for general inquiries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='cars.car')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='analytics_i_status_078d3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Actual sale price (may differ from listed price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_date', models.DateField(help_text='Date when the car was sold')),
                ('customer_name', models.CharField(help_text='Name of the customer who bought the car', max_length=200)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email address', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cars.car')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['-sale_date'], name='analytics_s_sale_da_6efdfb_idx')],
            },
        ),
    ]
