# Generated by Django 5.0.14 on 2025-11-11 15:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to brand logo image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(help_text='Car manufacturer (e.g., Toyota)', max_length=100)),
                ('model', models.CharField(help_text='Car model (e.g., Camry)', max_length=100)),
                ('year', models.IntegerField(help_text='Manufacturing year', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in your currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage', models.IntegerField(help_text='Mileage in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('vin', models.CharField(help_text='Vehicle Identification Number (17 characters)', max_length=17, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the car')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features (e.g., ["GPS", "Leather Seats", "Sunroof"])')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this car on homepage?')),
                ('views_count', models.IntegerField(default=0, help_text='Number of times this car was viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.category')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Cloudinary URL of the image')),
                ('cloudinary_public_id', models.CharField(help_text='Cloudinary public ID for deletion', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main display image?')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
                'ordering': ['order', 'uploaded_at'],
                'indexes': [models.Index(fields=['car', 'is_primary'], name='cars_carima_car_id_4b6ae5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['make', 'model'], name='cars_car_make_3ceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['year'], name='cars_car_year_fc6735_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price'], name='cars_car_price_f6b08b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='cars_car_status_3b4442_idx'),
        ),
    ]
