# Generated by Django 5.0.14 on 2025-11-11 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateField(help_text='Date when the repair/maintenance was performed')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost of this repair (sum of all parts + labor)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Overall description of what was done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(help_text='The car this maintenance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='cars.car')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-repair_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(help_text='Name of the part (e.g., "Brake Pads", "Oil Filter")', max_length=200)),
                ('part_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit of this part', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, help_text='Number of this part used', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this part')),
                ('maintenance_record', models.ForeignKey(help_text='The maintenance record this part belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='maintenance.maintenancerecord')),
            ],
            options={
                'verbose_name': 'Maintenance Part',
                'verbose_name_plural': 'Maintenance Parts',
                'ordering': ['part_name'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['car', '-repair_date'], name='maintenance_car_id_34771c_idx'),
        ),
    ]
